version: 0.2

phases: 
  build:
    commands:
      - echo "Build block"
      - ls
      - echo "Running tests to check if 'Congratulations' is present in index.html"
      - grep "Congratulations" index.html

  post_build:
    commands:
      - echo "Post build phase"

artifacts:
  files:
    - index.html
    - appspec.yml
    - scripts/**  # <-- Keep folder structure
